### ISSUE TITLE
The addon does not appear in Properties > Scene

### ISSUE THREAD

**Issue by ronvdlg** [Vinc3r/Polycount#21]
I can install and activate the addon from the polycount_2020.10.27.zip file in Blender 2.90.1, however, it does not appear in Properties > Scene.

Is it incompatible with Blender 2.90.1?

**Comment by Vinc3r** [comment]
Weird, I'm on 2.90.1 myself. I do another test.

You don't have any error message?

[edit] Fresh portable version of 2.90.1 here, no issue at all, so I will need more detail on your side to be able to help/debug

![image](https://user-images.githubusercontent.com/3873421/97967899-2ebc0d80-1dbe-11eb-91ce-f6527f707304.png)

**Comment by Vinc3r** [comment]
@rdllngr any news?

**Comment by Vinc3r** [comment]
@rdllngr ?
